site_name: saturio/duckdb-php

theme:
  name: readthedocs

docs_dir: docs/md

nav:
  - Intro:
      - 'index.md'
      - 'getting-started.md'
      - 'installation.md'
  - Usage:
      - 'running-queries.md'
      - 'read-resultset-content.md'
      - 'types.md'
      - 'prepared-statements.md'
      - 'appenders.md'
      - 'examples.md'
  - Guides:
      - 'opcache-preload.md'
      - 'upgrade-1-to-2.md'

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs/md
